### ISSUE TITLE
open source code

### ISSUE THREAD

**Issue by OliverHuang1220** [djiajunustc/TransVG#1]
Hi@djiajunustc 
Thank you for your excellent work! I'm very interested in your work. When will open source code be available？

**Comment by djiajunustc** [comment]
Hi，
The code is available now.
Thanks a lot.

**Comment by OliverHuang1220** [comment]
Thank you for your open source! I find you use 8GPUs，But I only have one NVIDIA 1080TI12GB,Can I run this project？

**Comment by djiajunustc** [comment]
I haven't conducted experiments with one GPU. But I think it should be okay. 
Maybe you can change the batch size to 16 or 32.

**Comment by OliverHuang1220** [comment]
Thanks for your reply. I will try it.

发自我的iPhone

**Comment by djiajunustc** [comment]
Hope it will help you : )
