### ISSUE TITLE
pretrained checkpoints

### ISSUE THREAD

**Issue by seanzhuh** [djiajunustc/TransVG#10]
Hello, in [Pretrained Checkpoints Gdrive](https://drive.google.com/drive/folders/1SOHPCCR6yElQmVp96LGJhfTP46RxVwzF), there is only 3 checkpoints, where detr-r50-gref.pth means resnet50-refcocog-google, detr-r50-unc.pth means resnet50-refcoco-unc, correct me if I'm wrong. Could you please release the pretrained resnet50 checkpoints for refcoco+/refcocog-umd and also, the resnet101.

**Comment by sean-zhuh** [comment]
Hi again, I've noticed that the performance in this repository is contradictory to that in your paper, where on RefCOCO TestB set, you claim in the paper that TransVG reaches ~78, however in this repo, it only achieves ~75. Overall, thanks for your great work. I do hope this result could be  updated on your paper (arxiv). The mismatched results between the repository and your paper may mislead readers and followers in the community.
