### ISSUE TITLE
What is the training hyper-parameters for Flickr-30k dataset？

### ISSUE THREAD

**Issue by jianghaojun** [djiajunustc/TransVG#13]
In [train.sh](https://github.com/djiajunustc/TransVG/blob/main/train.sh), I didn't the training command for Flickr-30k dataset. Could you please provide the training hyper-parameters for this dataset? Really appreciate your help!!!

**Comment by djiajunustc** [comment]
The are the same as ReferItGame.

**Comment by jianghaojun** [comment]
Thanks for your prompt reply!

**Comment by tiger990111** [comment]
> In [train.sh](https://github.com/djiajunustc/TransVG/blob/main/train.sh), I didn't the training command for Flickr-30k dataset. Could you please provide the training hyper-parameters for this dataset? Really appreciate your help!!!

Hi, do you have the split file of Flickr dataset? Split as: 29,783 train, 1000 validation, 1000 test.

**Comment by jianghaojun** [comment]
@tiger990111 Hi, I can send a download link to your email.

**Comment by tiger990111** [comment]
> @tiger990111 Hi, I can send a download link to your email.

Thank you! My email is wkang11@hawk.iit.edu
Thanks again!
