### ISSUE TITLE
Pretrained model for Flicker dataset

### ISSUE THREAD

**Issue by vinodkkurmi** [djiajunustc/TransVG#16]
Hi @djiajunustc ,
Can you please share the pretrained model for FLicker dataset?
For training the Flicker dataset, what should be used in place of "checkpoints/detr-r50-referit.pth".
I use detr-r50-referit.pth for training on Flicker datset for bachsize of 8, the ACC is about ~29%.
Can you please clarify and provide the pretrained  model. 
Thank you

**Comment by djiajunustc** [comment]
Hi,

It is extactly the detr-r50-referit.pth that I used to train on Flickr30K.
Since both ReferItGame and Flickr30K have no overlapping images with MSCOCO.
Maybe you should try it again.

**Comment by vinodkkurmi** [comment]
@djiajunustc 
Thank you for your reply. 
Can you please share the trained model( trained on Flicker30k).
Thank you

**Comment by djiajunustc** [comment]
Hi @vinodkkurmi,

Please check the Gdrive, the model trained on Flicker30K has been uploaded.

Best,
Jiajun Deng
