### ISSUE TITLE
Questions about the pretrained checkpoints of deter [ResNet-101 backbone].

### ISSUE THREAD

**Issue by 2o2o-2o2o** [djiajunustc/TransVG#20]
Hello, @djiajunustc 
Thank you for your excellent work! 
In [GDrive](https://drive.google.com/drive/folders/1SOHPCCR6yElQmVp96LGJhfTP46RxVwzF), there is only 3 pretrained checkpoints on detr-50 model. Could you please release the pretrained resnet101 checkpoints on all datasets. Could you please release the code of pretrain detr model on all datasets?

**Comment by djiajunustc** [comment]
These models have been released.
