### ISSUE TITLE
Question about training time

### ISSUE THREAD

**Issue by lmc8133** [djiajunustc/TransVG#25]
Thanks for your excellent work. I wonder how long do you training a epoch. And I want to ask if it's possible to do this task by using 2080ti GPU?

**Comment by djiajunustc** [comment]
It depends on the datasets. Maybe 12-20 minutes each epoch with 8 2080Ti GPUs.

**Comment by lmc8133** [comment]
Thank you for your reply!  And I want to ask about how many epochs can the model converge, because I can only use 4 2080ti GPUs, and I find it takes about 3 hours per epoch in training(refcoco dataset)。Whether it's too slow to do this task, And could you please give some advices to accelerate iterations without more GPUs?
