### ISSUE TITLE
Cannot load checkpoints correctly

### ISSUE THREAD

**Issue by zzh-tech** [djiajunustc/TransVG#30]
When I run evaluation code, I cannot load the checkpoints correctly.

> Missing key(s) in state_dict: "visumodel.transformer.encoder.layers.0.self_attn.in_proj_weight", 
"visumodel.transformer.encoder.layers.0.self_attn.in_proj_bias" ...
Unexpected key(s) in state_dict: "transformer.encoder.layers.0.self_attn.in_proj_weight", "transformer.encoder.layers.0.self_attn.in_proj_bias"...

**Comment by zzh-tech** [comment]
It seems that the provided checkpoints are for training. Could you please release the checkpoints for evaluation? Thanks in advance!

**Comment by zzh-tech** [comment]
Thanks for sharing the checkpoints!

**Comment by HelloWorld4747** [comment]
Hello, may I please ask you if you can share the checkpoints for evaluation with me by any chance? Thanks in advance! Looking forward to your response soon! Cheers!
