### ISSUE TITLE
Dataset referit

### ISSUE THREAD

**Issue by LeungWaiHo** [djiajunustc/TransVG#5]
Dear authors:
Thanks for your excellent work! I have great interest of your work, but when I try to download the Referit dataset according to the instruction file I find error because resource not found in "http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz". Could you provide some solutions? Thank you again!

**Comment by LeungWaiHo** [comment]
After training on UNC dataset, I would like to eval my trained weight but I receive an error:
ValueError: Dataset unc does not have split test, How can I solve it?

**Comment by djiajunustc** [comment]
Hi @LeungWaiHo ,
The dataset 'unc' refers to RefCOCO, which has val, testA and testB splits.
That's why the value is raised.
