### ISSUE TITLE
Data preparation

### ISSUE THREAD

**Issue by ShiFengyuan1999** [djiajunustc/TransVG#9]
I'm very interested in your work and try to reproduce the experimental results in the paper. But I cannot download the referit dataset through the link “http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz”. Could you provide a solution? Thanks a lot!

**Comment by djiajunustc** [comment]
The download link is invalid now. 
I'm not sure whether the copyright allows me to deliver the datasets publicly. 
You can leave your email address here and I'll send it to you.

**Comment by burningisnaive** [comment]
Hi @djiajunustc, I am also trying to reproduce to this paper, but I can not access these two link:
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Could you please sent me the dataset ? 
My mail address is M202072081@hust.edu.cn. Thank you very much !

**Comment by lmfethan** [comment]
Hi @djiajunustc , I hope to reproduce your work but your download link REFERIT_SPLITS_URL and REFERIT_DATA_URL are invalid. Could you mail me the dataset? My email address is: limf33@mail2.sysu.edu.cn. Thank you very much!

**Comment by vinodkkurmi** [comment]
Hi @djiajunustc, I am also trying to reproduce to this paper, but I can not access these two link:
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Could you please sent me the dataset ?
My mail address is vinod.kurmi@kuleuven.be Thank you very much !

**Comment by Liquor520** [comment]
Hi @djiajunustc, I am also trying to reproduce to this paper, but I can not access these two link:
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Could you please sent me the dataset ?
My mail address is 1481663704@qq.com Thank you very much !

**Comment by ztx2017** [comment]
Hello, author, I'm reproducing your code, but I can't run the code in download_data.sh, can you send the dataset set privately, thank you.
My email address is 1499978443@qq.com

**Comment by Erf1369** [comment]
Hi @djiajunustc, I am also trying to reproduce to this paper, but I can not access these two link:
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Could you please sent me the dataset ?
My mail address is erfan.ghadery@gmail.com Thank you very much !

**Comment by huangsiyong** [comment]
Hi @djiajunustc, I am also trying to reproduce to this paper, but I can not access these two link:
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Could you please sent me the dataset ?
My mail address is 1043305278@qq.com Thank you very much !

**Comment by LeungWaiHo** [comment]
> Hi @freedom6927, Please leave your email address here if ReferItGame data cannot be downloaded through this link.

My mail address is leungwaiho0515@163.com Thank you very much !

**Comment by zzy99** [comment]
Hi @djiajunustc, I am also trying to reproduce to this paper, but I can not access these two link:
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Could you please sent me the dataset ?
My mail address is 80431395@qq.com Thank you very much !

**Comment by kappa-maintainer** [comment]
Hello, I am trying to reproduce the paper, but $REFERIT_SPLITS_URL and $REFERIT_DATA_URL are invalid. Could you please send these two files to my email address pocketkirby2@gmail.com?

**Comment by uselessperso** [comment]
Hi @djiajunustc, I am also trying to reproduce to this paper, but I can not access these two link:
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Could you please sent me the dataset ?
My mail address is 1397595064@qq.com Thank you very much !

**Comment by sean-zhuh** [comment]
Hi @djiajunustc, I am also trying to reproduce to this paper, but I can not access these two link:
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Could you please sent me the dataset ?
My mail address is sean.zhuh@gmail.com Thank you very much !

**Comment by jianghaojun** [comment]
Hi @djiajunustc , I also encountered this problem, could you send me this dataset for reproduce your paper ? My email address is : 1608996023@qq.com. Thanks a lot!

**Comment by CloudyDory** [comment]
Hi @djiajunustc, I am also trying to reproduce to this paper, but I can not access these two link:
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Could you please sent me the dataset ?
My mail address is yunhui17@outlook.com Thank you very much !

**Comment by oli-21** [comment]
Hi @djiajunustc, I am also trying to reproduce to this paper, but I can not access these two link:
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Sorry to bother you but could you please sent me the dataset ?
My mail address is oli2157331j@outlook.com
Thank you very much !

**Comment by nj-czy** [comment]
Hi @djiajunustc, I am also trying to reproduce to this paper, but I can not access these two link:
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Sorry to bother you but could you please sent me the dataset ?
My mail address is 543620050@qq.com
Thank you very much !

**Comment by liu-tianxiang** [comment]
Hi @djiajunustc, I am also trying to reproduce to this paper, but I can not access these two link:
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Could you please sent me the dataset ?
My mail address is 2279566500@qq.com Thank you very much !

**Comment by Aliciawangyu** [comment]
> Hi @djiajunustc, I am also trying to reproduce to this paper, but I can not access these two link: REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2" REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz" Could you please sent me the dataset ? My mail address is Christine_Amber@163.com. Thank you very much !

**Comment by Aliciawangyu** [comment]
Hi @djiajunustc, I am also trying to reproduce to this paper, but I can not access these two link: REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2" REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz" Could you please sent me the dataset ? My mail address is [Christine_Amber@163.com](mailto:Christine_Amber@163.com). Thank you very much !

**Comment by 2horse9sun** [comment]
Hi @djiajunustc, I am also trying to reproduce to this paper, but I can not access these two link:
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Could you please sent me the dataset ?
My mail address is [jsjhfx@163.com](mailto:jsjhfx@163.com) Thank you very much !

**Comment by lmc8133** [comment]
Hi @djiajunustc, I am also trying to reproduce to this paper, but I can not access these two link:
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Sorry to bother you but could you please sent me the dataset ?
My mail address is [lmc8133@bupt.edu.cn](mailto:lmc8133@bupt.edu.cn). Thank you very much !

**Comment by nevinmusula** [comment]
Hey, share with me too... The REFER_SPLITS_URL and REFERIT_DATA_URL arent working

My email nevinmusula@gmail.com

Thank you

**Comment by FioPio** [comment]
Hey! Same here,

My email ferriol73pey@gmail.com,

Thank you

**Comment by akira-l** [comment]
Same problem in downloading dataset. Could you sent me the dataset? 
My email [liangyzh18@outlook.com](url) 
Thanks.

**Comment by litongbupt** [comment]
Hi @djiajunustc, I am also trying to reproduce to this paper, but I can not access these two link:
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Could you please sent me the dataset ?
My mail address is  litong.lt@alibaba-inc.com Thank you very much !

**Comment by Reyihua** [comment]
Hi @djiajunustc, I am also trying to reproduce to this paper, but I can not access these two link:
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Could you please sent me the dataset ?
My mail address is [417615845@qq.com). Thank you very much !

**Comment by NanAlbert** [comment]
Hi @djiajunustc, I am also trying to reproduce to this paper, but I can not access these two link:
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Could you please sent me the dataset ?
My mail address is [[gejn168@gmail.com](mailto:gejn168@gmail.com)). Thank you very much !

**Comment by tiger990111** [comment]
Hi @djiajunustc, I am also trying to reproduce to this paper, but I can not access these two link:
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Could you please sent me the dataset ?
My mail address is [wkang11@hawk.iit.edu](wkang11@hawk.iit.edu). Thank you very much !

**Comment by theuy** [comment]
Hi @djiajunustc, I am also trying to reproduce to this paper, but I can not access these two link:
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Could you please sent me the dataset ?
My mail address is tyhcjf@163.com Thank you very much !

**Comment by zhix9767** [comment]
Hi @djiajunustc, I am also trying to reproduce to this paper, but I can not access these two link:
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Could you please sent me the dataset ?
My mail address is [493077309@qq.com](mailto:493077309@qq.com)). Thank you very much !

**Comment by Yyq-Yuki** [comment]
Same problem in downloading dataset. Could you please sent me the dataset?
My email [liangyzh18@outlook.com](https://github.com/djiajunustc/TransVG/issues/url)
Thanks a lot!

**Comment by Yyq-Yuki** [comment]
Same problem in downloading dataset. Could you please sent me the dataset?
My email is yuqiyang@tom.com
Thanks a lot!

**Comment by xiaohuihui52309** [comment]
Hi @djiajunustc, I am also trying to reproduce to this paper, but I can not access these two link:
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Could you please sent me the dataset ?
My mail address is  xiaohuihui52309@163.com. Thank you very much !

**Comment by HelloWorld4747** [comment]
Hi @djiajunustc, I am also trying to reproduce this paper, but I can not access these two links: REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2" REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz" Could you please sent me the dataset? My mail address is 445788914@qq.com. Thank you very much!

**Comment by ho460kenya** [comment]
Hi @djiajunustc 
Same problems occur here.
Would you send me the dataset, please? My email addres is hoshimure.47@gmail.com . 
Thank you so much.

And @anyone. If you receive the dataset from the author, please consider to create a shared link.

**Comment by preetom-saha-arko** [comment]
Hi @djiajunustc , I am also trying to reproduce to this paper, but I can not access these two link:
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Could you please send me the dataset ?
My mail address is [arko@cse.buet.ac.bd](mailto:arko@cse.buet.ac.bd)). Thank you very much !

**Comment by satvik1406** [comment]
Hi @djiajunustc , I am also trying to reproduce to this paper, but I can not access these two link:
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Could you please send me the dataset ?
My mail address is [svuppala@umass.edu](mailto:svuppala@umass.edu)). Thank you very much !

**Comment by MCenyuan** [comment]
Hi @djiajunustc , I am also trying to reproduce to this paper, but I can not access these two link:
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Could you please send me the dataset ?
My mail address is  zhaoenyuan@stu.ouc.edu.cn   . Thank you very much !

**Comment by qwerjingyu** [comment]
Hi @djiajunustc , I am also trying to reproduce to this paper, but I can not access these two link:
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Could you please send me the dataset ?
My mail address is 790957220@qq.com . Thank you very much !

**Comment by WesleyZzx** [comment]
Hi @djiajunustc , I am also trying to reproduce to this paper, but I can not access these two link:
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Could you please send me the dataset ?
My mail address is crilias.zzx@gmail.com. Thank you very much !

**Comment by zy845047842** [comment]
Hi @djiajunustc , I am also trying to reproduce to this paper, but I can not access these two link:
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Could you please send me the dataset ?
My mail address is [zy845047842@gmail.com]. Thank you very much !

**Comment by Arandinglv** [comment]
Hi @djiajunustc , I am also trying to reproduce to this paper, but I can not access these two link:
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Could you please send me the dataset ?
My mail address is [arandinglv@gmail.com]. I would appreciate if you provide datasets!

**Comment by AIworkers** [comment]
@djiajunustc , I am trying to reproduce to this paper, but I can not access these two link:
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Could you please send me the dataset ?
My mail address is [[1989978344@qq.com)].Could you give me a help?

**Comment by O-VIGIA** [comment]
Hi @djiajunustc , I am also trying to reproduce this paper, but I can not access these two links:
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Could you please send me the datasets?
My email address is [[zhiyang@stu.xmu.edu.cn].](mailto:zhiyang@stu.xmu.edu.cn) I would appreciate it if you could provide datasets! 
THKS!

**Comment by chongjiliu2001** [comment]
Hi @djiajunustc , I am also trying to reproduce this paper, but I can not access these two links:
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Could you please send me the datasets?
My email address is 473710558@qq.com.   I would appreciate it if you could provide datasets!
THKS!

**Comment by Arandinglv** [comment]
I find the referit data in my BaiduNetDisk, the url is:

通过网盘分享的文件：referitdata.tar.gz
链接: https://pan.baidu.com/s/1-ECB0daXi-K1yLpBX0oNpw?pwd=h6js 提取码: h6js

I'm not sure if it is, but I only find this.

Good luck!


Seven ***@***.***> 于2024年9月19日周四 12:37写道：

**Comment by feng-zitong** [comment]
Hi @djiajunustc , I am also trying to reproduce this paper, but I can not access these two links:
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Could you please send me the datasets?
My email address is [1529084548@qq.com] I would appreciate it if you could provide datasets!
THKS!

**Comment by IceIce1ce** [comment]
I also cannot access to the dataset. My email address is: ctran159852@gmail.com. Can you send me a valid download link?

**Comment by z-ustin** [comment]
I also cannot access to the dataset. My email address is:541434186@qq.com  Can you send me a valid download link?
